// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqzxQrva7klt-IZ6GKYDQBt1N3QhqvXYI',
    appId: '1:807751337467:web:f941557d6467803fbe775e',
    messagingSenderId: '807751337467',
    projectId: 'inventorysystem-90d33',
    authDomain: 'inventorysystem-90d33.firebaseapp.com',
    storageBucket: 'inventorysystem-90d33.firebasestorage.app',
    measurementId: 'G-SMXZQ2ZSV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi8-24WPOGCWnZVVYsmDll-GBnZXNn0xo',
    appId: '1:807751337467:android:5bbdb468f6cefff8be775e',
    messagingSenderId: '807751337467',
    projectId: 'inventorysystem-90d33',
    storageBucket: 'inventorysystem-90d33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWyqPPjhsEVNDFB7g2Di3DhqZvSMxfrk4',
    appId: '1:807751337467:ios:5c594d53746c864cbe775e',
    messagingSenderId: '807751337467',
    projectId: 'inventorysystem-90d33',
    storageBucket: 'inventorysystem-90d33.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWyqPPjhsEVNDFB7g2Di3DhqZvSMxfrk4',
    appId: '1:807751337467:ios:5c594d53746c864cbe775e',
    messagingSenderId: '807751337467',
    projectId: 'inventorysystem-90d33',
    storageBucket: 'inventorysystem-90d33.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqzxQrva7klt-IZ6GKYDQBt1N3QhqvXYI',
    appId: '1:807751337467:web:8db3900881e168a2be775e',
    messagingSenderId: '807751337467',
    projectId: 'inventorysystem-90d33',
    authDomain: 'inventorysystem-90d33.firebaseapp.com',
    storageBucket: 'inventorysystem-90d33.firebasestorage.app',
    measurementId: 'G-291WRGXLTD',
  );
}
